local _, Graphit = ...

-- ===================================================================
-- AUTO-GENERATED by ExtractSettings.lua via /graphitdumpall.
-- WoW 12.0.5 build 67823 - 2026-06-12.
-- Do not edit by hand; re-run the dump after each client patch.
--
-- Layout: [metaCVar] = { [childCVar] = { min, max, [level]=value, ... } }
-- Values/min/max are OBSERVED, not engine limits (CVars accept any value).
-- For graphicsQuality the children are the Layer-2 meta CVars and the
-- values are their target levels (Layer 1->2).
-- ===================================================================
Graphit.generatedGraphicsData = {

-- graphicsViewDistance: 8 child CVar(s): TerrainLodDiv, entityLodDist, entityShadowFadeScale, farclip, horizonClip, horizonStart, terrainLodDist, wmoLodDist
["graphicsViewDistance"] = {
  ["TerrainLodDiv"] = { min="384", max="768", [0]="384", [1]="384", [2]="384", [3]="512", [4]="512", [5]="512", [6]="512", [7]="768", [8]="768", [9]="768" },
  ["entityLodDist"] = { min="5", max="10", [0]="5", [1]="5", [2]="5", [3]="7", [4]="8", [5]="8", [6]="10", [7]="10", [8]="10", [9]="10" },
  ["entityShadowFadeScale"] = { min="10", max="50", [0]="10", [1]="10", [2]="10", [3]="15", [4]="20", [5]="20", [6]="25", [7]="30", [8]="40", [9]="50" },
  ["farclip"] = { min="1500", max="10000", [0]="1500", [1]="2000", [2]="3000", [3]="5000", [4]="6000", [5]="6000", [6]="7000", [7]="8000", [8]="8000", [9]="10000" },
  ["horizonClip"] = { min="1500", max="10000", [0]="1500", [1]="2000", [2]="3000", [3]="5000", [4]="6000", [5]="6000", [6]="7000", [7]="8000", [8]="8000", [9]="10000" },
  ["horizonStart"] = { min="400", max="4000", [0]="400", [1]="600", [2]="800", [3]="1000", [4]="1400", [5]="1700", [6]="1900", [7]="2400", [8]="3000", [9]="4000" },
  ["terrainLodDist"] = { min="200", max="650", [0]="200", [1]="225", [2]="250", [3]="350", [4]="400", [5]="500", [6]="500", [7]="600", [8]="650", [9]="650" },
  ["wmoLodDist"] = { min="250", max="400", [0]="250", [1]="250", [2]="300", [3]="300", [4]="350", [5]="350", [6]="400", [7]="400", [8]="400", [9]="400" },
},

-- graphicsShadowQuality: 5 child CVar(s): shadowBlendCascades, shadowMode, shadowNumCascades, shadowSoft, shadowTextureSize
["graphicsShadowQuality"] = {
  ["shadowBlendCascades"] = { min="0", max="1", [0]="0", [1]="0", [2]="0", [3]="1", [4]="1", [5]="1" },
  ["shadowMode"] = { min="0", max="4", [0]="0", [1]="1", [2]="2", [3]="3", [4]="3", [5]="4" },
  ["shadowNumCascades"] = { min="1", max="4", [0]="1", [1]="1", [2]="2", [3]="3", [4]="3", [5]="4" },
  ["shadowSoft"] = { min="0", max="1", [0]="0", [1]="0", [2]="0", [3]="0", [4]="1", [5]="1" },
  ["shadowTextureSize"] = { min="1024", max="2048", [0]="1024", [1]="1024", [2]="1024", [3]="2048", [4]="2048", [5]="2048" },
},

-- graphicsLiquidDetail: 3 child CVar(s): reflectionMode, rippleDetail, waterDetail
["graphicsLiquidDetail"] = {
  ["reflectionMode"] = { min="0", max="3", [0]="0", [1]="0", [2]="0", [3]="3" },
  ["rippleDetail"] = { min="0", max="2", [0]="0", [1]="0", [2]="1", [3]="2" },
  ["waterDetail"] = { min="0", max="3", [0]="0", [1]="1", [2]="2", [3]="3" },
},

-- graphicsParticleDensity: 3 child CVar(s): particleDensity, particleMTDensity, weatherDensity
["graphicsParticleDensity"] = {
  ["particleDensity"] = { min="0", max="100", [0]="0", [1]="10", [2]="25", [3]="50", [4]="80", [5]="100" },
  ["particleMTDensity"] = { min="0", max="100", [0]="0", [1]="20", [2]="35", [3]="70", [4]="100", [5]="100" },
  ["weatherDensity"] = { min="0", max="3", [0]="0", [1]="0", [2]="1", [3]="1", [4]="3", [5]="3" },
},

-- graphicsSSAO: single child (SSAO); direct control, not expanded.

-- graphicsDepthEffects: 3 child CVar(s): DepthBasedOpacity, refraction, sunShafts
["graphicsDepthEffects"] = {
  ["DepthBasedOpacity"] = { min="0", max="1", [0]="0", [1]="1", [2]="1", [3]="1" },
  ["refraction"] = { min="0", max="2", [0]="0", [1]="0", [2]="1", [3]="2" },
  ["sunShafts"] = { min="0", max="2", [0]="0", [1]="0", [2]="1", [3]="2" },
},

-- graphicsComputeEffects: 4 child CVar(s): clusteredShading, particulatesEnabled, volumeFog, volumeFogLevel
["graphicsComputeEffects"] = {
  ["clusteredShading"] = { min="0", max="1", [0]="0", [1]="1", [2]="1", [3]="1", [4]="1" },
  ["particulatesEnabled"] = { min="0", max="1", [0]="0", [1]="1", [2]="1", [3]="1", [4]="1" },
  ["volumeFog"] = { min="0", max="1", [0]="0", [1]="1", [2]="1", [3]="1", [4]="1" },
  ["volumeFogLevel"] = { min="0", max="3", [0]="0", [1]="0", [2]="1", [3]="2", [4]="3" },
},

-- graphicsOutlineMode: single child (OutlineEngineMode); direct control, not expanded.

-- graphicsTextureResolution: 3 child CVar(s): componentTextureLevel, terrainMipLevel, worldBaseMip
["graphicsTextureResolution"] = {
  ["componentTextureLevel"] = { min="0", max="1", [0]="1", [1]="1", [2]="0" },
  ["terrainMipLevel"] = { min="0", max="1", [0]="1", [1]="1", [2]="0" },
  ["worldBaseMip"] = { min="0", max="2", [0]="2", [1]="1", [2]="0" },
},

-- graphicsSpellDensity: 2 child CVar(s): spellClutter, spellVisualDensityFilterSetting
["graphicsSpellDensity"] = {
  ["spellClutter"] = { min="1", max="4", [0]="1", [1]="2", [2]="4" },
  ["spellVisualDensityFilterSetting"] = { min="1", max="4", [0]="1", [1]="2", [2]="4" },
},

-- graphicsProjectedTextures: single child (projectedTextures); direct control, not expanded.

-- graphicsEnvironmentDetail: 4 child CVar(s): doodadLodScale, lodObjectCullSize, lodObjectFadeScale, lodObjectMinSize
["graphicsEnvironmentDetail"] = {
  ["doodadLodScale"] = { min="50", max="150", [0]="50", [1]="50", [2]="75", [3]="75", [4]="100", [5]="100", [6]="100", [7]="125", [8]="150", [9]="150" },
  ["lodObjectCullSize"] = { min="14", max="35", [0]="35", [1]="30", [2]="27", [3]="22", [4]="20", [5]="19", [6]="18", [7]="17", [8]="16", [9]="14" },
  ["lodObjectFadeScale"] = { min="50", max="150", [0]="50", [1]="50", [2]="80", [3]="80", [4]="90", [5]="90", [6]="100", [7]="110", [8]="125", [9]="150" },
  ["lodObjectMinSize"] = { min="0", max="30", [0]="0", [1]="0", [2]="0", [3]="0", [4]="0", [5]="0", [6]="0", [7]="0", [8]="30", [9]="20" },
},

-- graphicsGroundClutter: 2 child CVar(s): groundEffectDensity, groundEffectDist
["graphicsGroundClutter"] = {
  ["groundEffectDensity"] = { min="16", max="256", [0]="16", [1]="16", [2]="16", [3]="40", [4]="64", [5]="80", [6]="80", [7]="128", [8]="128", [9]="256" },
  ["groundEffectDist"] = { min="40", max="320", [0]="40", [1]="55", [2]="70", [3]="110", [4]="160", [5]="185", [6]="200", [7]="260", [8]="300", [9]="320" },
},

-- graphicsQuality: master -> meta CVar level (Layer 1->2)
["graphicsQuality"] = {
  ["graphicsViewDistance"] = { min="0", max="9", [0]="0", [1]="1", [2]="2", [3]="3", [4]="4", [5]="5", [6]="6", [7]="7", [8]="8", [9]="9" },
  ["graphicsShadowQuality"] = { min="0", max="5", [0]="0", [1]="0", [2]="0", [3]="1", [4]="2", [5]="3", [6]="3", [7]="4", [8]="5", [9]="5" },
  ["graphicsLiquidDetail"] = { min="0", max="3", [0]="0", [1]="0", [2]="1", [3]="1", [4]="2", [5]="2", [6]="2", [7]="2", [8]="2", [9]="3" },
  ["graphicsParticleDensity"] = { min="0", max="5", [0]="0", [1]="1", [2]="1", [3]="2", [4]="3", [5]="4", [6]="4", [7]="5", [8]="5", [9]="5" },
  ["graphicsSSAO"] = { min="0", max="4", [0]="0", [1]="0", [2]="0", [3]="1", [4]="2", [5]="3", [6]="3", [7]="4", [8]="4", [9]="4" },
  ["graphicsDepthEffects"] = { min="0", max="3", [0]="0", [1]="0", [2]="0", [3]="1", [4]="2", [5]="3", [6]="3", [7]="3", [8]="3", [9]="3" },
  ["graphicsComputeEffects"] = { min="0", max="4", [0]="0", [1]="0", [2]="1", [3]="1", [4]="2", [5]="2", [6]="3", [7]="3", [8]="4", [9]="4" },
  ["graphicsOutlineMode"] = { min="0", max="2", [0]="0", [1]="0", [2]="0", [3]="0", [4]="1", [5]="1", [6]="2", [7]="2", [8]="2", [9]="2" },
  ["graphicsTextureResolution"] = { min="0", max="2", [0]="0", [1]="1", [2]="1", [3]="1", [4]="2", [5]="2", [6]="2", [7]="2", [8]="2", [9]="2" },
  ["graphicsSpellDensity"] = { min="0", max="2", [0]="0", [1]="0", [2]="0", [3]="1", [4]="1", [5]="1", [6]="1", [7]="2", [8]="2", [9]="2" },
  ["graphicsProjectedTextures"] = { min="0", max="1", [0]="0", [1]="1", [2]="1", [3]="1", [4]="1", [5]="1", [6]="1", [7]="1", [8]="1", [9]="1" },
  ["graphicsEnvironmentDetail"] = { min="0", max="9", [0]="0", [1]="1", [2]="2", [3]="3", [4]="4", [5]="5", [6]="6", [7]="7", [8]="8", [9]="9" },
  ["graphicsGroundClutter"] = { min="0", max="9", [0]="0", [1]="1", [2]="2", [3]="3", [4]="4", [5]="5", [6]="6", [7]="7", [8]="8", [9]="9" },
},

}